### ISSUE TITLE
Ragdolls for players?

### ISSUE THREAD

**Issue by caoqt1** [anchurcn/gsphysics#1]
I used the HL1RagdollMod goldsource project and i went into the phys file in vs2019 and changed the scientist from scientist to gordon (hl1 multiplayer player model) and added the ragdoll and compiled it and when i played and i died in multiplayer i did not ragdoll, any help?

**Comment by anchurcn** [comment]
The latest version has provided the player ragdoll function, and has also written a collision editor based on the unity editor.

**Comment by anchurcn** [comment]
I will push my work.

**Comment by caoqt1** [comment]
> The latest version has provided the player ragdoll function, and has also written a collision editor based on the unity editor.

Good job! Is there a download link so i can test with it?

**Comment by caoqt1** [comment]
Or is it still unfinished?
